### ISSUE TITLE
Authentication using Microsoft Identity Platform

### ISSUE THREAD

**Issue by dafi-blinkhealth** [BingAds/BingAds-Python-SDK#119]
According to the documentation (https://docs.microsoft.com/en-us/bingads/guides/authentication-oauth-identity-platform?view=bingads-12), BingAdsSDK is moving to Microsoft Identity Platform for authentication. However, following through the authentication examples in this code, it seems like it is still expecting Client ID from Live Connect 

Error example from get_access_token:
`Bingads.exceptions.OAuthTokenRequestException: error_code: invalid_client, error_description: The client does not exist. If you are the application developer, configure a new application through the application management site at https://apps.dev.microsoft.com/` 

Even though the client ID exists in the Azure Portal.

Are there other functions that supports the Microsoft Identity Platform? Or it has not been implemented yet?

**Comment by qitia** [comment]
Thanks for reaching out @dafi-blinkhealth. You are right this has not been completely supported in SDK. We will announce this with SDK release notes when it is supported.

**Comment by eric-urban** [comment]
@dafi-blinkhealth the error you mentioned could also be due to mismatch of environment e.g., you registered the app at https://apps.dev.microsoft.com/ but are using the sandbox auth endpoint login.live-int.com, or vice versa. Can you please double check your environment?

Can you successfully obtain an access token and complete the documented [Quick Start](https://docs.microsoft.com/en-us/advertising/guides/get-started#quick-start) for production or sandbox? If not, where does authentication fail and what is the error?

**Comment by qitia** [comment]
@dafi-blinkhealth did you try method @eric-urban provides? We published version 12.13.2 which support microsoft identity 5/15. Maybe you could check if it works for you.

**Comment by qitia** [comment]
close for now. @dafi-blinkhealth please reopen it if you still find issue on this.
