### ISSUE TITLE
Date time errors with "valid" dates

### ISSUE THREAD

**Issue by bmoe872** [BingAds/BingAds-Python-SDK#176]
I'm sending over conversion data that we get directly from Google for our offline conversions. The offline conversion time is in UTC, but I'm getting responses back from the soap API as such:
`Message: The conversion time must be later than the click time.`

I don't have control over the "click time", so I'm curious how this could even happen? These errors didn't start cropping up until after daylights savings time on Sunday, so my hunch is there's something up with that, but since it appears that bing is taking UTC and I'm getting UTC it should "just work", but it's not. 

Unless I'm missing something else?

The tracking ID on my latest push is:
`TrackingId: bd326b2c-8790-48c4-84d0-dd21462dff90.`

Additionally I'm seeing the error `The date and time for the click ID is outside the conversion window for this goal.`

Which again shouldn't be possible. The data I'm getting is for the last 7 days, and our conversion window is the last 7 days. 

Any help is greatly appreciated.

**Comment by qitia** [comment]
the log I found for this tracking id is:
```
code="5601" message="The list of offline conversions exceeds the limit."
```
Seems like you are sending more than 1000 offline conversion in a single request, are you seeing the difference @bmoe872 .

**Comment by qitia** [comment]
@bmoe872 -
We search from the log using the same UID/CID as used in trackingiD: bd326b2c-8790-48c4-84d0-dd21462dff90, and do found some errors as you mentioned. But we are not logging the actual data of the request, could you please share the payload of the request for us to debug more?

**Comment by bmoe872** [comment]
Hi @qitia thanks for the response. I noticed I was sending too many at one point, but I went down to sending them in batches of 800 to mitigate this. I'll get the payload here shortly and send.

**Comment by bmoe872** [comment]
This file contains the first 800 entries we have. (We have over 4000 entries at this point), but these 800 are giving me the same error. 

[clk_id_data.txt](https://github.com/BingAds/BingAds-Python-SDK/files/6172103/clk_id_data.txt)

**Comment by bmoe872** [comment]
Actually I just added 1hr and 30min to our conversion times and that seems to have alleviated the issue. This wasn't an issue before, and our times are in UTC. It sounds like the MSCLK times are not in UTC?

**Comment by qitia** [comment]
We dig this issue more(attach the data with click time) and found there do exist records where conversion time earlier than the click time. Which is impossible and that is why those records failed. example:

d1b1fac3e46518cd761e9a8caff64560 | 2021-3-15 11:57:07 | 2021-3-15 11:53:27
-- | -- | --



1) we confirm that we handle both click time and conversion time with same timezone;
2) Click time is generated when the ads get clicked;
3) Error "The date and time for the click ID is outside the conversion window for this goal." is possible although the data you are  getting is for the last 7 days, and our conversion window is the last 7 days... because the conversion time is within 7 days, we do not check click time for this goal.


[OfflineConversions.xlsx](https://github.com/BingAds/BingAds-Python-SDK/files/6282878/OfflineConversions.xlsx)

**Comment by bmoe872** [comment]
Great, but this only started happening after day lights savings time. Our time is stored in UTC, what time is yours stored in?

**Comment by qitia** [comment]
The Click Time we encoded into MS click id is also in UTC.
