### ISSUE TITLE
WARNING:suds.client:Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.

### ISSUE THREAD

**Issue by vp-at-st** [BingAds/BingAds-Python-SDK#238]
**Method:** 
campaign_update_response = cmp_service.UpdateCampaigns(AccountId=ACCOUNT_ID, Campaigns=campaigns)

Language: python

**ERROR:**
suds.WebFault: Server raised fault: 'The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.'

**DO NOT CLOSE THE ISSUE UNTIL IT IS FULLY RESOLVED**

**Comment by vp-at-st** [comment]
@qitia

**Comment by vp-at-st** [comment]
code to showcase how **campaigns** veriable is defined:

ACCOUNT_ID = 1111111
customer_id = 22222

auth_data_2, cmp_service = auth_helper.get_service_client(
    service_type="CampaignManagementService",
    account_id=ACCOUNT_ID,
    customer_id=customer_id,
)

campaigns = cmp_service.factory.create("ArrayOfCampaign")
campaign = cmp_service.factory.create("Campaign")

campaign.FinalUrlSuffix = "test=test_test_test_{device}"
campaign.Id = 111111111

campaigns.Campaign.append(campaign)

**Comment by qitia** [comment]
could you please share the trackingid/requestid?

**Comment by vp-at-st** [comment]
No, I don't have it.
The response didn't have a tracking ID

**Comment by qitia** [comment]
Besides "Parameter 'Campaigns' is required and hasn't been found" error, I cannot find any other errors with the same customerid as "e1d7dd3b-0fba-4141-a742-b0fc0cb6b6a8". 

Could you please share your AccountId, CustomerId, Devtoken and the timestamp when you hit the error? You can send to BingAdsSDK <bing_ads_sdk@microsoft.com> directly instead of sharing here.

Or, if your issue persists, you can reach the support team for help.

**Comment by vp-at-st** [comment]
Sent the requested information to the email address.

You didn't answer the question from our previous thread: 
**We are using an account with API USER permissions to authenticate with the API. Could this be the reason why we can't update the Campaign?
Should we use SUPER ADMIN or perhaps an ADVERTISER CAMPAIGN MANAGER?**

Screenshot from User Management:
![image](https://user-images.githubusercontent.com/121902307/224719329-88518c2d-f543-40e5-b8b8-59e8e750c6da.png)

**Comment by qitia** [comment]
I am not 100% about this question because I did not see any log for your request. But since you mentioned this works for GetCampaigns, So I do not think this is the reason.

With the info you shared via email, I still cannot see any log of your UpdateCampaigns call. I am afraid you need to reach the support team for help.

**Comment by qitia** [comment]
I am not 100% about this question because I did not see any log for your request. But since you mentioned this works for GetCampaigns, So I do not think this is the reason. let me involve our service team for help in the email thread.
