### ISSUE TITLE
Bing latest version 

### ISSUE THREAD

**Issue by nmylarappa** [BingAds/BingAds-Python-SDK#92]
I see that the latest version is 12. When would this  version be available?

**Comment by qitia** [comment]
we've already support V12 since version 11.12.1. The SDK support both version 11 and 12 now. @nmylarappa

**Comment by VishaldasM** [comment]
Hi ,this is regarding bing api upgrade from 12 to 13 version as published in this web page (https://docs.microsoft.com/en-us/advertising/guides/migration-guide?view=bingads-13#reporting)we are running on 11.12.4 at present. we tried to upgrade to the latest version and we are getting below error. (we are using python 2.7)(bingenv)skumar@east1-prod-dwhadmin-1:~$ pip install -U bingads
Collecting bingads
 Using cached https://files.pythonhosted.org/packages/7b/e5/c09900391ca26baf290151e63c092535be96d79ab83ad3cbc5797fb89fd2/bingads-12.13.6.zip
 Complete output from command python setup.py egg_info:
 error in bingads setup command: ‘install_requires’ must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in enum34;python_version<“3.4” at ;python_version<“3.4" ----------------------------------------
Command “python setup.py egg_info” failed with error code 1 in /tmp/pip-build-NMxDFY/bingadswe are able to upgrade till 12.0.1 but not to any higher version than that.

Could someone look into it if we are missing anything?

**Comment by qitia** [comment]
Looking. +@Eric Urban<mailto:Eric.Urban@microsoft.com> is there any know escalation or similar?

Thanks,
Qingjun

**Comment by eric-urban** [comment]
@nmylarappa @qitia a similar issue was resolved as noted [here](https://github.com/sdispater/pendulum/issues/187). I hope this helps!

**Comment by VishaldasM** [comment]
Hi Team,

we upgraded bing version to 13 and tried to launch our jobs. we get below error. do we have different access levels for 13 version compared to previous versions ? (doesn't make much sense but this is what we are observing)
we are able to execute same bing jobs on degraded version even today with the same credentials but getting access issues on 13 version.

Below is the exact error for reference:

/home/hkoppuravuri/virtual/bing_v/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:380: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
SNIMissingWarning,
/home/hkoppuravuri/virtual/bing_v/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecurePlatformWarning,
error_code: invalid_grant, error_description: AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: 187438c4-f3ed-4e94-8b00-158288a31a00
Correlation ID: 2db347ca-39c4-4c91-98c1-d0117e66b071
Timestamp: 2019-10-29 05:59:22Z

Can you please help us on this..

**Comment by eric-urban** [comment]
@VishaldasM you might need new access and refresh tokens via the user consent flow. please note as of version [12.13.2](https://github.com/BingAds/BingAds-Python-SDK/releases/tag/v12.13.2): The default OAuth endpoint is updated from Live Connect endpoint to the Microsoft Identity endpoint for developers. The Microsoft Identity endpoint supports both Microsoft Account (MSA) personal credentials and Azure Active Directory (AAD) work credentials. For more information, see [Upgrade to the Microsoft identity platform endpoint FAQ](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth#upgrade-identity-platform-faq).
